defaults: &defaults
  capture_path: <%= File.expand_path('~/Movies/Game Capture HD Library/') %>
  output_path: <%= File.expand_path('~/ika/') %>

  create_markers:
    use_parallel: true
    concurrency: <%= c = Parallel.processor_count - 1; c < 1 ? 1 : c %>
    # 同時に何枚づつ処理を行なうか。
    # TODO: OSの空きメモリを見てGC.startを走らせるようにする。
    batch_size: 1000
    gc_timing: 1

  default_scale: 8
  create_youtube_playlist_dates: 3

  # Elgatoのディレクトリも消すかどうか
  # ただしElgatoアプリが起動中の場合に削除すると,Elgatoのアプリを終了した際jsonが作られてしまう。
  delete_capture_dir: true

  # 抽出したビデオファイルを消すか
  delete_video_file: true

  playlist_check_seconds: 10

  videos_per_page: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
